# CMake generated Testfile for 
# Source directory: /workspaces/dealii/tests/quick_tests
# Build directory: /workspaces/dealii/tests/quick_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(step.debug "/usr/bin/cmake" "-DTRGT=step.debug.run" "-DTEST=step.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(step.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;91;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(step.release "/usr/bin/cmake" "-DTRGT=step.release.run" "-DTEST=step.release" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(step.release PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;91;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(affinity.debug "/usr/bin/cmake" "-DTRGT=affinity.debug.run" "-DTEST=affinity.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(affinity.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;95;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(tbb.debug "/usr/bin/cmake" "-DTRGT=tbb.debug.run" "-DTEST=tbb.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(tbb.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;104;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(taskflow.debug "/usr/bin/cmake" "-DTRGT=taskflow.debug.run" "-DTEST=taskflow.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(taskflow.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;109;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(lapack.debug "/usr/bin/cmake" "-DTRGT=lapack.debug.run" "-DTEST=lapack.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(lapack.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;140;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(umfpack.debug "/usr/bin/cmake" "-DTRGT=umfpack.debug.run" "-DTEST=umfpack.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(umfpack.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;145;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(gsl.debug "/usr/bin/cmake" "-DTRGT=gsl.debug.run" "-DTEST=gsl.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(gsl.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;150;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(arpack.debug "/usr/bin/cmake" "-DTRGT=arpack.debug.run" "-DTEST=arpack.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(arpack.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;160;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(sundials-ida.debug "/usr/bin/cmake" "-DTRGT=sundials-ida.debug.run" "-DTEST=sundials-ida.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(sundials-ida.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;170;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(assimp.debug "/usr/bin/cmake" "-DTRGT=assimp.debug.run" "-DTEST=assimp.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(assimp.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;175;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(boost_zlib.debug "/usr/bin/cmake" "-DTRGT=boost_zlib.debug.run" "-DTEST=boost_zlib.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(boost_zlib.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;190;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
add_test(gmsh.debug "/usr/bin/cmake" "-DTRGT=gmsh.debug.run" "-DTEST=gmsh.debug" "-DBINARY_DIR=/workspaces/dealii" "-P" "/workspaces/dealii/cmake/scripts/run_test.cmake")
set_tests_properties(gmsh.debug PROPERTIES  ENVIRONMENT "OMPI_MCA_rmaps_base_oversubscribe=1" LABEL "sanity checks" WORKING_DIRECTORY "/workspaces/dealii/tests/quick_tests" _BACKTRACE_TRIPLES "/workspaces/dealii/tests/quick_tests/CMakeLists.txt;75;ADD_TEST;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;195;make_quicktest;/workspaces/dealii/tests/quick_tests/CMakeLists.txt;0;")
