name: doxygen documentation

on: [push, pull_request]

jobs:
  linux-release-serial:
    # simple serial release build using g++

    name: transltor for documentation
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        rm -rf CMakeCache.txt CMakeFiles
        cmake  -DDEAL_II_COMPONENT_DOCUMENTATION=ON -DDEAL_II_DOXYGEN_USE_MATHJAX=ON .
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: linux-serial-detailed.log
        path: detailed.log
    - name: build
      run: |
        sudo apt-get install libboost-all-dev doxygen python
        make documentation
    
    - name: Publish Doxygen documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
